server:
  port: 8085
  
spring:
 application:
    name: 'user'
 data:
   mongodb:
     uri: mongodb://localhost:27017/db_user         

eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:8082/eureka

security:
  oauth2:
    resource:
      user-info-uri: http://localhost:8081/token
      

